version: "3.7"

services:
  peripheral-manager-modbus:
    build: .
    restart: on-failure
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
